//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace top.ebiz.service
{
    public partial class BZ_DOC_FILE_ATTACHMENT
    {
        public Nullable<decimal> DF_ID { get; set; }
        public string? DH_CODE { get; set; }
        public string? DF_NAME { get; set; }
        public string? DF_PATH { get; set; }
        public string? DF_FULLNAME { get; set; }
        public string? DF_REMARK { get; set; }
        public string? CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string? TOKEN_UPDATE { get; set; }
    }

    public partial class BZ_DOC_FILE
    {
        public Nullable<decimal> DF_ID { get; set; }
        public string? DH_CODE { get; set; }
        public string? DF_NAME { get; set; }
        public string? DF_PATH { get; set; }
        public string? DF_REMARK { get; set; }
        public string? CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string? TOKEN_UPDATE { get; set; }
    }


}
